name: Sync LeetCode Submissions

on:
  schedule:
    - cron: "0 23 * * *"   
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Sync LeetCode submissions
        uses: joshcai/leetcode-sync@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          leetcode-csrftoken: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          destination-folder: "."
      - name: Commit and push changes
        run: |
          git config --global user.name "Rispa Joseph"
          git config --global user.email "rizpahjoseph@gmail.com"
          git add .
          git commit -m "Sync LeetCode submissions" || echo "No changes"
          git push
